"""
Simple script to add IT jobs - Run with: python manage.py shell < add_jobs_simple.py
"""
from myapp.models import Job
from datetime import date, timedelta

deadline = date.today() + timedelta(days=30)

IT_JOBS = [
    # SOFTWARE DEVELOPMENT
    {'title': 'Senior Python Developer', 'company_name': 'TechCorp Solutions', 'description': 'We are looking for an experienced Python Developer to join our dynamic team. You will be responsible for developing scalable web applications, APIs, and backend services using Python frameworks.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹15,00,000 - ₹25,00,000 per annum', 'requirements': 'Bachelors degree in Computer Science. 3+ years of Python development.', 'skills_required': 'Python, Django, Flask, REST APIs, PostgreSQL, Docker, Git', 'responsibilities': 'Design and implement backend services. Write clean code.', 'benefits': 'Health Insurance, Flexible working, Remote options', 'vacancies': 3, 'is_featured': True},
    {'title': 'Full Stack JavaScript Developer', 'company_name': 'InnovateTech', 'description': 'Join our team as a Full Stack Developer with modern JavaScript technologies.', 'location': 'Hyderabad, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹8,00,000 - ₹15,00,000 per annum', 'requirements': 'Strong JavaScript/TypeScript. React and Node.js experience.', 'skills_required': 'JavaScript, TypeScript, React, Node.js, MongoDB, Express.js', 'responsibilities': 'Develop responsive web apps. Build RESTful APIs.', 'benefits': 'Medical insurance, Gym, Free meals', 'vacancies': 5, 'is_featured': True},
    {'title': 'Java Backend Developer', 'company_name': 'Enterprise Solutions Ltd', 'description': 'Skilled Java Developer for enterprise-grade applications.', 'location': 'Pune, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹12,00,000 - ₹20,00,000 per annum', 'requirements': 'B.Tech/M.Tech in CS. Strong Java skills.', 'skills_required': 'Java, Spring Boot, Microservices, Kafka, MySQL, AWS', 'responsibilities': 'Design microservices. Implement CI/CD.', 'benefits': 'Health insurance, Performance bonus', 'vacancies': 4, 'is_featured': False},
    {'title': 'Android Developer', 'company_name': 'MobileFirst Apps', 'description': 'Build high-quality mobile applications with Android.', 'location': 'Mumbai, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹7,00,000 - ₹12,00,000 per annum', 'requirements': 'Android development experience. Kotlin proficiency.', 'skills_required': 'Kotlin, Java, Android SDK, Jetpack Compose, Firebase', 'responsibilities': 'Develop and maintain Android apps.', 'benefits': 'Learning budget, Flexible hours', 'vacancies': 2, 'is_featured': False},
    {'title': 'iOS Developer', 'company_name': 'Apple Innovations', 'description': 'Create iOS applications using Swift and SwiftUI.', 'location': 'Chennai, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹8,00,000 - ₹14,00,000 per annum', 'requirements': 'Strong Swift and iOS SDK knowledge.', 'skills_required': 'Swift, SwiftUI, UIKit, Core Data, REST APIs, Xcode', 'responsibilities': 'Build iOS apps from scratch.', 'benefits': 'MacBook provided, Health insurance', 'vacancies': 2, 'is_featured': False},
    {'title': 'React Native Developer', 'company_name': 'CrossPlatform Tech', 'description': 'Build cross-platform mobile apps for iOS and Android.', 'location': 'Delhi NCR, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹9,00,000 - ₹16,00,000 per annum', 'requirements': 'React Native development experience.', 'skills_required': 'React Native, JavaScript, TypeScript, Redux, Firebase', 'responsibilities': 'Develop cross-platform mobile apps.', 'benefits': 'Remote work, Medical coverage', 'vacancies': 3, 'is_featured': False},
    # DATA SCIENCE & ML
    {'title': 'Data Scientist', 'company_name': 'DataDriven Analytics', 'description': 'Develop predictive models and derive insights from datasets.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹18,00,000 - ₹30,00,000 per annum', 'requirements': 'Masters/PhD in Statistics or CS.', 'skills_required': 'Python, R, TensorFlow, PyTorch, Scikit-learn, SQL, Pandas', 'responsibilities': 'Build predictive models. Analyze datasets.', 'benefits': 'Research allowance, Conference sponsorship', 'vacancies': 2, 'is_featured': True},
    {'title': 'Machine Learning Engineer', 'company_name': 'AI Solutions Inc', 'description': 'Design, build, and deploy ML models at scale.', 'location': 'Hyderabad, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹20,00,000 - ₹35,00,000 per annum', 'requirements': 'Strong ML/AI background.', 'skills_required': 'Python, TensorFlow, PyTorch, MLflow, Kubernetes, AWS SageMaker', 'responsibilities': 'Design ML pipelines. Train and optimize models.', 'benefits': 'GPU workstations, Remote work, ESOPs', 'vacancies': 3, 'is_featured': True},
    {'title': 'Data Analyst', 'company_name': 'Business Insights Co', 'description': 'Transform raw data into actionable insights.', 'location': 'Mumbai, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹6,00,000 - ₹12,00,000 per annum', 'requirements': 'Bachelors degree. SQL and Excel proficiency.', 'skills_required': 'SQL, Excel, Power BI, Tableau, Python, Statistics', 'responsibilities': 'Analyze data. Create reports and dashboards.', 'benefits': 'Health insurance, Flexible timing', 'vacancies': 4, 'is_featured': False},
    {'title': 'AI Research Scientist', 'company_name': 'DeepMind India', 'description': 'Push boundaries of artificial intelligence research.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '5-10', 'salary': '₹40,00,000 - ₹70,00,000 per annum', 'requirements': 'PhD in AI/ML or related field.', 'skills_required': 'PyTorch, TensorFlow, Python, Deep Learning, Reinforcement Learning', 'responsibilities': 'Conduct research. Publish papers.', 'benefits': 'World-class facilities, Conference travel', 'vacancies': 2, 'is_featured': True},
    # CLOUD & DEVOPS
    {'title': 'Cloud Solutions Architect', 'company_name': 'CloudFirst Technologies', 'description': 'Design and implement cloud architecture solutions.', 'location': 'Pune, India', 'job_type': 'full-time', 'experience_required': '5-10', 'salary': '₹25,00,000 - ₹45,00,000 per annum', 'requirements': 'Extensive AWS/Azure/GCP experience.', 'skills_required': 'AWS, Azure, GCP, Terraform, Docker, Kubernetes, Security', 'responsibilities': 'Design cloud architectures. Lead migrations.', 'benefits': 'Certification sponsorship, Premium insurance', 'vacancies': 2, 'is_featured': True},
    {'title': 'DevOps Engineer', 'company_name': 'Agile Ops Solutions', 'description': 'Build and maintain CI/CD pipelines. Automate infrastructure.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹15,00,000 - ₹28,00,000 per annum', 'requirements': 'Strong Linux skills. Container orchestration.', 'skills_required': 'Docker, Kubernetes, Jenkins, GitHub Actions, Terraform, Ansible, AWS', 'responsibilities': 'Build CI/CD pipelines. Manage containers.', 'benefits': 'Remote work, Learning budget', 'vacancies': 4, 'is_featured': False},
    {'title': 'Site Reliability Engineer', 'company_name': 'ScaleUp Systems', 'description': 'Ensure reliability of distributed systems.', 'location': 'Hyderabad, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹18,00,000 - ₹32,00,000 per annum', 'requirements': 'Large-scale distributed systems experience.', 'skills_required': 'Python, Go, Kubernetes, Prometheus, Grafana, ELK Stack', 'responsibilities': 'Ensure reliability. Implement monitoring.', 'benefits': 'On-call compensation, Remote flexibility', 'vacancies': 3, 'is_featured': False},
    {'title': 'AWS Cloud Engineer', 'company_name': 'Amazon Web Services Partner', 'description': 'Design, deploy, and manage AWS infrastructure.', 'location': 'Chennai, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹10,00,000 - ₹18,00,000 per annum', 'requirements': 'AWS certifications preferred.', 'skills_required': 'AWS EC2, S3, Lambda, RDS, VPC, CloudFormation, IAM', 'responsibilities': 'Deploy AWS infrastructure. Manage resources.', 'benefits': 'AWS certification sponsorship', 'vacancies': 5, 'is_featured': False},
    # CYBERSECURITY
    {'title': 'Cybersecurity Analyst', 'company_name': 'SecureNet Solutions', 'description': 'Protect enterprise systems from cyber threats.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹8,00,000 - ₹15,00,000 per annum', 'requirements': 'Understanding of security concepts.', 'skills_required': 'SIEM, Firewalls, IDS/IPS, Network Security, Incident Response', 'responsibilities': 'Monitor alerts. Investigate incidents.', 'benefits': 'Security certification sponsorship', 'vacancies': 4, 'is_featured': False},
    {'title': 'Penetration Tester', 'company_name': 'EthicalHack Pro', 'description': 'Identify vulnerabilities in applications.', 'location': 'Mumbai, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹15,00,000 - ₹28,00,000 per annum', 'requirements': 'OSCP/CEH certification.', 'skills_required': 'Burp Suite, Metasploit, Nmap, Kali Linux, Web App Security', 'responsibilities': 'Conduct penetration tests. Write reports.', 'benefits': 'Bug bounty bonus, Certification support', 'vacancies': 2, 'is_featured': True},
    {'title': 'Security Engineer', 'company_name': 'CryptoShield Tech', 'description': 'Design and implement security solutions.', 'location': 'Delhi NCR, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹18,00,000 - ₹30,00,000 per annum', 'requirements': 'Security engineering background.', 'skills_required': 'Cryptography, OAuth, SAML, Security Architecture, Python', 'responsibilities': 'Design solutions. Conduct reviews.', 'benefits': 'Remote work, Premium insurance', 'vacancies': 2, 'is_featured': False},
    # DATABASE & BACKEND
    {'title': 'Database Administrator', 'company_name': 'DataCore Systems', 'description': 'Manage and optimize database systems.', 'location': 'Pune, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹12,00,000 - ₹22,00,000 per annum', 'requirements': 'Strong database administration experience.', 'skills_required': 'MySQL, PostgreSQL, MongoDB, Redis, Database Optimization', 'responsibilities': 'Manage databases. Optimize queries.', 'benefits': 'Health insurance, Performance bonus', 'vacancies': 2, 'is_featured': False},
    {'title': 'Big Data Engineer', 'company_name': 'DataLake Analytics', 'description': 'Build and maintain big data pipelines.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹18,00,000 - ₹32,00,000 per annum', 'requirements': 'Big data technologies experience.', 'skills_required': 'Apache Spark, Hadoop, Kafka, Airflow, Python, Scala, AWS EMR', 'responsibilities': 'Build data pipelines. Optimize processing.', 'benefits': 'Remote work, Learning budget', 'vacancies': 3, 'is_featured': True},
    # WEB DEVELOPMENT
    {'title': 'Frontend Developer', 'company_name': 'Creative Web Studio', 'description': 'Create stunning user interfaces with modern technology.', 'location': 'Mumbai, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹6,00,000 - ₹12,00,000 per annum', 'requirements': 'Strong HTML, CSS, and JavaScript.', 'skills_required': 'React, Vue.js, HTML5, CSS3, SASS, JavaScript, TypeScript', 'responsibilities': 'Build responsive UIs. Collaborate with designers.', 'benefits': 'Flexible hours, Remote work option', 'vacancies': 4, 'is_featured': False},
    {'title': 'WordPress Developer', 'company_name': 'Digital Agency Pro', 'description': 'Develop custom WordPress themes and plugins.', 'location': 'Delhi, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹4,00,000 - ₹8,00,000 per annum', 'requirements': 'WordPress development experience.', 'skills_required': 'WordPress, PHP, MySQL, HTML, CSS, JavaScript, WooCommerce', 'responsibilities': 'Develop WordPress sites. Create themes.', 'benefits': 'Flexible timing, Health insurance', 'vacancies': 3, 'is_featured': False},
    {'title': 'UI/UX Designer', 'company_name': 'DesignFirst Agency', 'description': 'Design beautiful and intuitive user interfaces.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹7,00,000 - ₹14,00,000 per annum', 'requirements': 'Portfolio showcasing UI/UX work.', 'skills_required': 'Figma, Adobe XD, Sketch, Wireframing, Prototyping, User Research', 'responsibilities': 'Create UI designs. Conduct user research.', 'benefits': 'Design tool licenses, Learning budget', 'vacancies': 2, 'is_featured': False},
    # QA
    {'title': 'QA Engineer', 'company_name': 'Quality Tech Labs', 'description': 'Ensure software quality through comprehensive testing.', 'location': 'Noida, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹5,00,000 - ₹10,00,000 per annum', 'requirements': 'Manual and automated testing experience.', 'skills_required': 'Selenium, TestNG, JIRA, Postman, SQL, API Testing', 'responsibilities': 'Write test cases. Execute tests. Report bugs.', 'benefits': 'Health insurance, Learning opportunities', 'vacancies': 5, 'is_featured': False},
    {'title': 'Automation Test Engineer', 'company_name': 'AutoTest Solutions', 'description': 'Build and maintain automated test frameworks.', 'location': 'Hyderabad, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹10,00,000 - ₹18,00,000 per annum', 'requirements': 'Strong programming skills.', 'skills_required': 'Selenium, Python, Java, Cypress, Jest, Jenkins, Git', 'responsibilities': 'Build automation frameworks. Write tests.', 'benefits': 'Remote work, Annual bonus', 'vacancies': 3, 'is_featured': False},
    # PROJECT MANAGEMENT
    {'title': 'Technical Project Manager', 'company_name': 'Agile Projects Inc', 'description': 'Lead technical projects from inception to delivery.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '5-10', 'salary': '₹20,00,000 - ₹35,00,000 per annum', 'requirements': 'PMP/Scrum certification preferred.', 'skills_required': 'Agile, Scrum, JIRA, Confluence, Risk Management', 'responsibilities': 'Plan and track projects. Manage resources.', 'benefits': 'Leadership training, Health insurance', 'vacancies': 2, 'is_featured': False},
    {'title': 'Business Analyst', 'company_name': 'Tech Consulting Group', 'description': 'Bridge the gap between business and technology.', 'location': 'Pune, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹10,00,000 - ₹18,00,000 per annum', 'requirements': 'Requirements gathering experience.', 'skills_required': 'Requirements Analysis, UML, JIRA, Agile, SQL, Documentation', 'responsibilities': 'Gather requirements. Create documentation.', 'benefits': 'Flexible hours, Health insurance', 'vacancies': 3, 'is_featured': False},
    {'title': 'Scrum Master', 'company_name': 'Agile Transformation Co', 'description': 'Facilitate agile practices across development teams.', 'location': 'Chennai, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹12,00,000 - ₹22,00,000 per annum', 'requirements': 'CSM/PSM certification.', 'skills_required': 'Scrum, Agile, JIRA, Confluence, Coaching, Facilitation', 'responsibilities': 'Facilitate scrum events. Coach team members.', 'benefits': 'Certification support, Remote work', 'vacancies': 2, 'is_featured': False},
    # NETWORKING
    {'title': 'Network Engineer', 'company_name': 'NetConnect Solutions', 'description': 'Design, implement, and maintain network infrastructure.', 'location': 'Delhi NCR, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹10,00,000 - ₹18,00,000 per annum', 'requirements': 'CCNA/CCNP certification.', 'skills_required': 'Cisco, Juniper, Firewalls, VPN, TCP/IP, BGP, OSPF', 'responsibilities': 'Configure network devices. Monitor performance.', 'benefits': 'Certification sponsorship, Health insurance', 'vacancies': 3, 'is_featured': False},
    {'title': 'System Administrator', 'company_name': 'IT Infrastructure Corp', 'description': 'Manage and maintain server infrastructure.', 'location': 'Mumbai, India', 'job_type': 'full-time', 'experience_required': '3-5', 'salary': '₹8,00,000 - ₹15,00,000 per annum', 'requirements': 'Linux and Windows servers experience.', 'skills_required': 'Linux, Windows Server, VMware, Active Directory, Bash, PowerShell', 'responsibilities': 'Maintain servers. Manage user accounts.', 'benefits': 'Health insurance, Shift allowance', 'vacancies': 3, 'is_featured': False},
    # BLOCKCHAIN & EMERGING
    {'title': 'Blockchain Developer', 'company_name': 'CryptoTech Labs', 'description': 'Develop decentralized applications and smart contracts.', 'location': 'Bangalore, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹12,00,000 - ₹25,00,000 per annum', 'requirements': 'Blockchain development experience.', 'skills_required': 'Solidity, Ethereum, Web3.js, Smart Contracts, Rust, DeFi', 'responsibilities': 'Develop smart contracts. Build dApps.', 'benefits': 'Crypto rewards, Remote work', 'vacancies': 3, 'is_featured': True},
    {'title': 'IoT Developer', 'company_name': 'SmartDevices Inc', 'description': 'Build IoT solutions connecting hardware and software.', 'location': 'Hyderabad, India', 'job_type': 'full-time', 'experience_required': '1-3', 'salary': '₹8,00,000 - ₹15,00,000 per annum', 'requirements': 'IoT platforms experience.', 'skills_required': 'Arduino, Raspberry Pi, MQTT, Python, C/C++, AWS IoT', 'responsibilities': 'Develop IoT apps. Integrate sensors.', 'benefits': 'Hardware lab access, Learning budget', 'vacancies': 2, 'is_featured': False},
    # SUPPORT
    {'title': 'Technical Support Engineer', 'company_name': 'SupportFirst Solutions', 'description': 'Provide technical support to customers.', 'location': 'Gurgaon, India', 'job_type': 'full-time', 'experience_required': '0-1', 'salary': '₹3,50,000 - ₹6,00,000 per annum', 'requirements': 'Good communication skills.', 'skills_required': 'Troubleshooting, Windows, Networking Basics, Communication', 'responsibilities': 'Handle support tickets. Troubleshoot issues.', 'benefits': 'Shift allowance, Training provided', 'vacancies': 10, 'is_featured': False},
    {'title': 'IT Helpdesk Engineer', 'company_name': 'Corporate IT Services', 'description': 'Support internal IT operations.', 'location': 'Noida, India', 'job_type': 'full-time', 'experience_required': '0-1', 'salary': '₹3,00,000 - ₹5,00,000 per annum', 'requirements': 'Basic IT knowledge.', 'skills_required': 'Windows, Office 365, Hardware Troubleshooting, Active Directory', 'responsibilities': 'Resolve helpdesk tickets. Set up workstations.', 'benefits': 'Training programs, Career growth', 'vacancies': 8, 'is_featured': False},
    # INTERNSHIPS
    {'title': 'Software Development Intern', 'company_name': 'TechStart Labs', 'description': 'Gain hands-on experience in software development.', 'location': 'Bangalore, India', 'job_type': 'internship', 'experience_required': '0-1', 'salary': '₹15,000 - ₹25,000 per month stipend', 'requirements': 'Currently pursuing B.Tech/M.Tech.', 'skills_required': 'Python, Java, JavaScript, Git, Data Structures', 'responsibilities': 'Work on projects. Learn from mentors.', 'benefits': 'Mentorship, Certificate, PPO possibility', 'vacancies': 10, 'is_featured': False},
    {'title': 'Data Science Intern', 'company_name': 'Analytics Academy', 'description': 'Learn data science in a practical environment.', 'location': 'Hyderabad, India', 'job_type': 'internship', 'experience_required': '0-1', 'salary': '₹20,000 - ₹30,000 per month stipend', 'requirements': 'Basic Python and statistics knowledge.', 'skills_required': 'Python, Pandas, NumPy, Machine Learning Basics, SQL', 'responsibilities': 'Analyze datasets. Build simple models.', 'benefits': 'Learning resources, Certificate, PPO possibility', 'vacancies': 5, 'is_featured': False},
    # REMOTE
    {'title': 'Remote Full Stack Developer', 'company_name': 'GlobalTech Remote', 'description': 'Work remotely as a full stack developer.', 'location': 'Remote (India)', 'job_type': 'remote', 'experience_required': '3-5', 'salary': '₹18,00,000 - ₹35,00,000 per annum', 'requirements': 'Excellent communication. Self-motivated.', 'skills_required': 'React, Node.js, Python, PostgreSQL, AWS, Docker, Git', 'responsibilities': 'Develop full stack features. Global team collaboration.', 'benefits': 'Work from anywhere, Flexible hours, Equipment allowance', 'vacancies': 5, 'is_featured': True},
    {'title': 'Remote DevOps Consultant', 'company_name': 'Cloud Consulting Partners', 'description': 'Provide DevOps consulting services remotely.', 'location': 'Remote (India)', 'job_type': 'remote', 'experience_required': '5-10', 'salary': '₹25,00,000 - ₹50,00,000 per annum', 'requirements': 'Expert-level DevOps skills.', 'skills_required': 'AWS, Azure, Kubernetes, Terraform, CI/CD, Docker', 'responsibilities': 'Consult for clients. Design solutions.', 'benefits': 'Remote work, High compensation, Diverse projects', 'vacancies': 3, 'is_featured': True},
    # CONTRACT
    {'title': 'Contract Python Developer', 'company_name': 'Project Solutions Ltd', 'description': '6-month contract for Python developer.', 'location': 'Bangalore, India', 'job_type': 'contract', 'experience_required': '3-5', 'salary': '₹1,50,000 - ₹2,00,000 per month', 'requirements': 'Strong Python skills. 6-month availability.', 'skills_required': 'Python, Django, FastAPI, PostgreSQL, Docker, AWS', 'responsibilities': 'Develop backend services. Meet deadlines.', 'benefits': 'Competitive pay, Extension possibility', 'vacancies': 2, 'is_featured': False},
    {'title': 'Contract UI Developer', 'company_name': 'Design Agency Pro', 'description': '3-month contract for UI developer.', 'location': 'Mumbai, India', 'job_type': 'contract', 'experience_required': '1-3', 'salary': '₹80,000 - ₹1,20,000 per month', 'requirements': 'Portfolio of UI work.', 'skills_required': 'React, HTML5, CSS3, JavaScript, Responsive Design, Git', 'responsibilities': 'Build user interfaces. Cross-browser compatibility.', 'benefits': 'Flexible hours, Portfolio building', 'vacancies': 3, 'is_featured': False},
]

created = 0
for job in IT_JOBS:
    job['application_deadline'] = deadline
    Job.objects.create(**job)
    created += 1
    print(f"Created: {job['title']}")

print(f"\n{'='*50}")
print(f"Total jobs created: {created}")
print(f"Total jobs in database: {Job.objects.count()}")
