# Generated by Django 5.1.7 on 2025-10-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='name',
            new_name='role',
        ),
    ]
